name: Docker Image CI

on:
  release:
    types: [created]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Yandex Cloud
      id: login-cr
      uses: yc-actions/yc-cr-login@v2
      with:
          yc-sa-json-credentials: ${{ secrets.YANDEX_CLOUD_KEY }} # Ensure this secret is set in your repository settings
    
    - name: Set Image Tag
      id: set_tag
      run: echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      env:
        CR_REGISTRY: crpe51e4v7vs5p6ahf5m
        CR_REPO: go-uuid

        IMAGE_HASH: ${{ github.sha }}
        RELEASE_TAG: ${{ github.event.release.tag_name }}
      run: |
        export DOCKER_IMAGE_LATEST_TAG=cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPO }}:latest
        export DOCKER_IMAGE_HASH_TAG=cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPO }}:${{ env.IMAGE_HASH }}
        export DOCKER_IMAGE_RELEASE_TAG=cr.yandex/${{ env.CR_REGISTRY }}/${{ env.CR_REPO }}:${{ env.RELEASE_TAG }}

        docker build . --file Dockerfile --tag $DOCKER_IMAGE_HASH_TAG
        docker tag $DOCKER_IMAGE_HASH_TAG $DOCKER_IMAGE_LATEST_TAG
        docker tag $DOCKER_IMAGE_HASH_TAG $DOCKER_IMAGE_RELEASE_TAG
        docker push $DOCKER_IMAGE_HASH_TAG
        docker push $DOCKER_IMAGE_LATEST_TAG
        docker push $DOCKER_IMAGE_RELEASE_TAG